[package]
name = "alexeylegasov63/leafframeworkrbx"
description = "LeafFramework is a lightweight modular Roblox framework inspired by Flamework (Roblox-TS)"
version = "0.2.4"
license = "MIT"
authors = ["AlexeyLegasov63"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "src", 
    "src/**", 
    "CHANGELOG", 
    "LICENSE", 
    "default.project.json", 
    "wally.toml"
]

[dependencies]
Promise = "evaera/promise@4.0.0"